### ISSUE TITLE
Change Tile Size from 100 to 400.

### ISSUE THREAD

**Issue by JayTWWM** [shamim-akhtar/jigsaw-puzzle#1]
Not really an issue, but can you please help me with this. I've changed everything and still my game isn't working properly. I wanna change the tile size to 400. Here's how it comes out......

![Screenshot (11)](https://user-images.githubusercontent.com/54232875/150331931-efebaec0-fd20-4762-bcdd-57f43246f458.png)

**Comment by halovn113** [comment]
Don't know you fixed it yet. For someone who still find the answer: Just adjust the interval parameter in Tile.cs. 
For dynamic case: 
+ Make 2 variables A and B: A = current TileSize (width) / 100f, B = current TileSize (height) / 100f.
+ Then use 1 divided by the largest number between A and B, then we has C.
+ Use C to multiple 0.001f. 
Done, use that number to replace the current interval  value, we has the best result. 
![image](https://github.com/shamim-akhtar/jigsaw-puzzle/assets/35524746/f6bd6406-4703-43f1-bcca-dd75a4de2be8)

**Comment by JayTWWM** [comment]
Yeah fixed it a long time ago! Thanks anyways!
